### ISSUE TITLE
swagger 2.0 support for Play

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-play#13]
The current swagger-api group implementations for play don't support swagger 2.0.  There are a number of different efforts on this front that will hopefully converge on the best possible integration.

The previous (swagger-1.2) support was very "java-ish", requiring annotations in the code, etc., and bundled in a bunch of java-specific libraries which were not used by Play.  It would be best to have support for Play that's more scala-centric, and uses the swagger-specification as the routing logic, similar to [swagger-inflector](https://github.com/swagger-api/swagger-inflector).

**Comment by fehguy** [comment]
It looks like https://github.com/zalando/play-swagger has @jroper contributing to it, so this will likely be a solid project for swagger + Play

**Comment by jroper** [comment]
The Zalando effort is mostly being done without me, I just helped get them started with how to integrate into Play's sbt build, and have done some technical reviews.  It takes a swagger specification and generates a routes file, as well as case classes and other stubs.

**Comment by benmccann** [comment]
Ideally the implementation would be Java/Scala agnostic or for the parts that aren't there would be both Java support and Scala support.

**Comment by benmccann** [comment]
As far as pulling in unnecessary libraries, `swagger-play` currently depends on `swagger-jaxrs` which shouldn't be necessary since Play doesn't implement jaxrs. It's doing that to use `JaxrsApiReader` which seems to read the Swagger annotations and really doesn't appear to have much to do with jaxrs. Maybe there's some possibility we could rename `JaxrsApiReader` to `AnnotationReader` and move it to another library, so that we could use it without the jaxrs dependencies.

The dependency on `jsr311-api` seems unnecessary, so I've sent a [PR to remove it](https://github.com/swagger-api/swagger-play/pull/18).

I suppose those are sort of short term improvements if there's going to be major rewrite in the style of swagger-inflector, but doesn't hurt to do a bit of cleanup in the meantime.

**Comment by benmccann** [comment]
This is difficult because there's a lot of code that was deleted when moving to 2.0 without a clear explanation of how to migrate to the newer API https://github.com/swagger-api/swagger-core/commit/e978638b0edd36ba6e7a77209f7abc810ca38b7a

**Comment by benmccann** [comment]
PR for this issue: https://github.com/swagger-api/swagger-play/pull/23

**Comment by josephearl** [comment]
Thanks @benmccann!

**Comment by benmccann** [comment]
@fehguy can we close this as fixed now?

**Comment by fehguy** [comment]
happy to!
